
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devhub-qc-apps-pipeline
  description: CI/CD pipeline for DevHub QC Apps
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/RockStarDeveloperHub/devhub-qc-apps/blob/main/ci-cd/pipeline.yaml
spec:
  type: service
  lifecycle: production
  owner: aws
